const products = [
    {
      id: "1",
      name: "Wireless Bluetooth Headphones",
      category: "Electronics",
      price: 59.99,
      description: "High-quality wireless Bluetooth headphones with noise-cancellation.",
      rating: 4.5,
      stock: 25,
      imageURL: "https://www.boat-lifestyle.com/cdn/shop/products/main2_b66dce6b-710d-49cb-9d1c-2bc8c9c0ab15_600x.png?v=1645698328",
      isFeatured: true,
    },
    {
      id: "2",
      name: "Running Shoes",
      category: "Fashion",
      price: 89.99,
      description: "Comfortable and lightweight running shoes for daily exercise.",
      rating: 4.2,
      stock: 10,
      imageURL: "https://static.nike.com/a/images/t_default/d0e15fdf-cd8f-4020-8235-f31a0e07068e/W+NIKE+REVOLUTION+7.png",
      isFeatured: false,
    },
    {
      id: "3",
      name: "Smartwatch",
      category: "Electronics",
      price: 129.99,
      description: "Advanced smartwatch with heart rate monitor and GPS tracking.",
      rating: 4.7,
      stock: 5,
      imageURL: "https://www.boat-lifestyle.com/cdn/shop/files/2_c74d7f07-c10d-48ad-9da0-5e229499bad7.png?v=1694153692",
      isFeatured: true,
    },
    {
      id: "4",
      name: "Coffee Machine",
      category: "Home Appliances",
      price: 49.99,
      description: "Programmable coffee maker with brew strength control.",
      rating: 4.3,
      stock: 15,
      imageURL: "https://media.croma.com/image/upload/v1705921289/Croma%20Assets/Small%20Appliances/Food%20Processors/Images/245684_0_ng4sza.png",
      isFeatured: false,
    },
    {
      id: "5",
      name: "Gaming Keyboard",
      category: "Electronics",
      price: 69.99,
      description: "RGB mechanical gaming keyboard with customizable lighting.",
      rating: 4.6,
      stock: 20,
      imageURL: "https://media.croma.com/image/upload/v1689155034/Croma%20Assets/Computers%20Peripherals/Computer%20Accessories%20and%20Tablets%20Accessories/Images/259519_0_q2m9vy.png",
      isFeatured: true,
    },
    {
      id: "6",
      name: "Yoga Mat",
      category: "Fitness",
      price: 19.99,
      description: "Eco-friendly, non-slip yoga mat with carrying strap.",
      rating: 4.4,
      stock: 50,
      imageURL: "https://www.arka4u.com/wp-content/uploads/2018/12/4.png",
      isFeatured: false,
    },
    {
      id: "7",
      name: "Laptop Stand",
      category: "Accessories",
      price: 34.99,
      description: "Adjustable laptop stand with ergonomic design.",
      rating: 4.8,
      stock: 30,
      imageURL: "https://www.amkette.com/cdn/shop/files/hi-rise-stand-hero-image.png?v=1708681921",
      isFeatured: true,
    },
    {
      id: "8",
      name: "Smart LED Bulb",
      category: "Home Appliances",
      price: 15.99,
      description: "Wi-Fi enabled smart LED bulb with multiple color options.",
      rating: 4.1,
      stock: 40,
      imageURL: "https://i03.appmifile.com/422_item_in/04/07/2024/109d2f07b639c8164303dee5e44eaffc!800x800!85.png",
      isFeatured: false,
    },
    {
      id: "9",
      name: "Water Bottle",
      category: "Outdoor",
      price: 12.99,
      description: "Insulated stainless steel water bottle with 24-hour cold retention.",
      rating: 4.3,
      stock: 100,
      imageURL: "https://bisleri-shop-storage.s3.ap-south-1.amazonaws.com/products/June2024/q7YzCtJaRU7iDTU9SkZ7.png",
      isFeatured: false,
    },
    {
      id: "10",
      name: "Desk Lamp",
      category: "Home Decor",
      price: 22.99,
      description: "LED desk lamp with adjustable brightness and USB charging port.",
      rating: 4.2,
      stock: 12,
      imageURL: "https://orientelectric.com/cdn/shop/files/Ellipse_Desk_lamp.png?v=1728970428",
      isFeatured: false,
    },
  ];
  

  export default products